Fix arc.py.  Solves the following exceptions:
/.../mdtraj/formats/arc.pyc in load_arc(filename, top, stride, atom_indices)
     73     mdtraj.ArcTrajectoryFile :  Low level interface to TINKER .arc files
     74     """
---> 75     from mdtraj.trajectory import _parse_topology, Trajectory
     76
     77     # we make it not required in the signature, but required here.  although this

ImportError: No module named trajectory

/.../mdtraj/formats/arc.pyc in load_arc(filename, top, stride, atom_indices)
     87
     88     topology = _parse_topology(top)
---> 89     atom_indices = _cast_indices(atom_indices)
     90     if atom_indices is not None:
     91         topology = topology.subset(atom_indices)

NameError: global name '_cast_indices' is not defined